### ISSUE TITLE
coroutines and synchonized blocks

### ISSUE THREAD

**Issue by publicocean0** [vsilaev/tascalate-javaflow#2]
Hi 
I would like ask you for a opinion. 

i thought to use  a coroutine(your lib): it  receives a stream from network. This stream use inside synchonized blocks from receiving a bytearray. 

```
public static final class MyCoroutine implements Runnable {
    
    
    @Override
    public void run() {
      while(!inputstream.eof()){ 
      byte[] data=received_data(inputstream)
      process(data).
      }
    
   });
}

}

```
could it work?
1) when you instrument the class , does instrumentation handle synchonized blocks so the thread is not blocked but instead  it suspends the coroutine?
2) if the point 1 is yes, pratically the coroutine is suspended and resumed just inside synchonized blocks( in java code). Consider now the `process(data)` method similar to:
 ```
  process(data){
     synchonized (lock){
          ....
          native_jni_method(data);
          ....
    }
  } 
```
  the lock is in java code but inside that block there is also a native method. Theoretically i image the frame status  never contains native_jni_method because the lock eventually suspends the block before to native_jni_method. 
So i image all is working correctly. 

My assumptions are correct?

**Comment by vsilaev** [comment]
Hello,

Yes, synchronized blocks are handled and monitors are exited/re-entered on suspend/resume correspondingly. So no problems should be here.

Regarding native methods -- unless you do a crazy things like marking a native method as continuable and suspending right in native methods then everything should work as expected.

So both of your assumptions are correct

**Comment by publicocean0** [comment]
It is fantastic!. Quasar actually doesnt instrument synchonized blocks,wait/notify blocks. My initial idea is to use many coroutines instead to use many threads because it is more scalable.
I thought  i could realize a scheduler in which i can push many coroutines. 
Pratically it is a coroutines pool inside the same thread.

When a corotuine is blocked by a wait() instruction it is not necessary to block the thread but it is sufficient to suspend it. 
When a corotuine is suspended , it is taken another  coroutine ready to be resumed. In this way the thread is never blocked ... and the global performance will be very high.

For this reason is important to instrument synchronized blocks. You told you instrument synchonized block and  wait/notify so I suppose you internally realized a scheduler for switching from a corotuine to another. Pratically all my idea is already realized by you. I need not to implement a scheduler but just to create a new corotuine inside a thread. The remaining is automatic. Do you comfirm it? i can start to use your library in this way.

**Comment by vsilaev** [comment]
> Do you comfirm you instrumented also notify/wait? i can start to use your library in this way.

No, for the library `wait()/notify()` are just regular method calls. It doesn't go that far to automatically transform multi-threaded code into single-threaded coroutines.

So in the following block:
```java
synchronized (lock) {
  Continuation.suspend();
  lock.wait();
}
```
the method first will enter monitor, then suspended and exited monitor, then resumed (from outside) and monitor will be re-entered, finally it will start wait and blocks thread. No magic here.

The typical scenario to convert multi-threaded code into coroutine is:
```
// in continuable method
// Consumer part
if (!someDataReady()) {
  Data data = Continuation.suspend(new DataRequest());
  // Now data should be provided from outside, i.e. continuation caller
  workWithData(data);
}
...
// in continuation caller:
Continuation c = Continuation.startWith(method);
Object replyFromContinuation = c.value();
// Producer part
if (replyFromContinuation  instanceof DataRequest) {
  DataRequest dataRequest = (DataRequest)replyFromContinuation;
  Data data = produceData(dataRequest);
  cc.resume(data);
}
```

Hope that this helps you.

**Comment by publicocean0** [comment]
Unfurtunatelly in my case i have a ton of source (non only directly written by me, but also external libraries ) using internally locks. It is not practicable to modidy all sources for adapting them to coroutine. Sincerelly i see just a way: patch instrumenter. 
Thereoretically the monitor restoring is always correct because a lock can be competed by multiple coroutines in different threads.  The wait/notify (theoretically also sleep/join) instead is handled by scheduler. To realize the scheduler might be not so difficult. I can do fastly.The worrying part is to patch the instrumenter. Conceptually it is simple to replace methods, in the reality I have to study asm and your code that might be not so simple for me :) It is better that i begins to pray. ahaha

**Comment by vsilaev** [comment]
It sounds like your patch requires changes to the following two files (mostly):
https://github.com/vsilaev/tascalate-javaflow/blob/master/net.tascalate.javaflow.providers.asm5/src/main/java/org/apache/commons/javaflow/providers/asm5/ContinuableMethodVisitor.java
https://github.com/vsilaev/tascalate-javaflow/blob/master/net.tascalate.javaflow.providers.asm5/src/main/java/org/apache/commons/javaflow/providers/asm5/ContinuableMethodNode.java

What instrumenter do is: create a state machine to save/load state before suspend / after resume for method calls these are marked as continuable. That's it. But, sure, manipulating bytecode looks a bit cryptic :)

**Comment by publicocean0** [comment]
Thanks :)  the general idea is clear but since yesterday i began to frequent church :)
